"use client";
import { useEffect, useState } from "react";
import type { ReviewRun } from "../lib/types";
import { toMarkdown } from "../lib/review";
const sample = `diff --git a/src/auth.ts b/src/auth.ts\nindex 9b6f..bc29 100644\n--- a/src/auth.ts\n+++ b/src/auth.ts\n@@ -1,8 +1,10 @@\n export async function login(email: string, password: string) {\n-  const user = await db.users.findOne({ email, password });\n+  console.log("login", email, password);\n+  const query = \`SELECT * FROM users WHERE email = '\${email}' AND password = '\${password}'\`;\n+  const user = await db.query(query);\n   if (!user) {\n     throw new Error("Invalid credentials");\n   }\n+  return { token: btoa(email) };\n   return user;\n }`;
export default function Home() { const [diff,setDiff]=useState(sample), [run,setRun]=useState<ReviewRun|null>(null), [busy,setBusy]=useState(false), [error,setError]=useState(""); const [visible,setVisible]=useState(0);
  useEffect(()=>{ if(!run) return; setVisible(0); const id=setInterval(()=>setVisible(x=>x>=run.steps.length?x:x+1),500); return()=>clearInterval(id);},[run]);
  async function review(){setBusy(true);setError("");setRun(null);try{const res=await fetch("/api/review",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({diff})});const body=await res.json();if(!res.ok)throw new Error(body.error||"Review failed");setRun(body);}catch(e){setError(e instanceof Error?e.message:"Review failed");}finally{setBusy(false)}}
  const verdict=run?.findings.some(f=>f.severity==="P0")?"BLOCK MERGE":"REVIEW READY";
  return <main className="shell"><header style={{marginBottom:24}}><span className="pill" style={{background:"#312e81"}}>AGENTIC CODING · DEMO READY</span><h1 style={{fontSize:40,margin:"12px 0 4px"}}>Fix-It</h1><p style={{color:"var(--muted)",maxWidth:680}}>Paste a unified diff. Watch a review agent plan, analyse, patch and verify—without pretending it ran your repository.</p></header><section className="grid"><div className="card"><label htmlFor="diff"><b>Unified diff</b></label><textarea id="diff" value={diff} onChange={e=>setDiff(e.target.value)} aria-describedby="diff-help"/><p id="diff-help" style={{color:"var(--muted)",fontSize:13}}>Bundled auth fixture is pre-filled. Demo requires no login or API key.</p><button className="btn" onClick={review} disabled={busy||!diff.trim()}>{busy?"Reviewing…":"Review & Fix"}</button></div><div className="card"><h2 style={{marginTop:0}}>Agent Log</h2>{!run&&<p style={{color:"var(--muted)"}}>Start a review to see the agent’s work.</p>}{run?.steps.slice(0,visible).map((s,i)=><div key={s.name} style={{borderLeft:"2px solid #8b5cf6",padding:"0 0 16px 12px"}}><b>{i+1}. {s.name}</b><div style={{color:"var(--muted)",fontSize:14}}>{s.detail}</div></div>)}{run&&visible<run.steps.length&&<p aria-live="polite">Agent is working…</p>}</div>{error&&<p role="alert" className="wide" style={{color:"#fda4af"}}>{error}</p>}{run&&<><section className="card wide"><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",flexWrap:"wrap"}}><h2 style={{margin:0}}>Verdict: <span style={{color:verdict==="BLOCK MERGE"?"#fb7185":"#86efac"}}>{verdict}</span></h2><button className="btn secondary" onClick={()=>navigator.clipboard.writeText(toMarkdown(run))}>Copy report (Markdown)</button></div><p style={{color:"var(--muted)"}}>“Run tests” is a simulated heuristic in every mode. No pasted code is executed.</p></section><section className="card"><h2 style={{marginTop:0}}>Findings</h2>{run.findings.map(f=><article className={`finding ${f.severity.toLowerCase()}`} key={`${f.file}${f.line}${f.title}`}><span className="pill" style={{background:f.severity==="P0"?"#881337":"#854d0e"}}>{f.severity}</span> <code>{f.file}:{f.line}</code><h3 style={{margin:"8px 0 4px"}}>{f.title}</h3><p>{f.why}</p><p style={{color:"#c4b5fd"}}><b>Suggested fix:</b> {f.fix}</p></article>)}</section><section className="card"><h2 style={{marginTop:0}}>Proposed patch</h2><pre>{run.patch}</pre><h2>Fail → pass test log</h2><pre style={{color:"#fda4af"}}>{run.testLog.before}</pre><hr style={{borderColor:"var(--line)"}}/><pre style={{color:"#86efac",marginTop:12}}>{run.testLog.after}</pre></section></>}</section></main> }
